dist: xenial
language: node_js
sudo: false
node_js:
  - "8"

# Run the app locally using docker
before_script:
 - docker-compose up -d
 - sleep 3
 - docker restart angular-api

script: 
 - npm run speedTest
 # Always fails
 #  - npm run reliabilityTest